[package]
name = "ekiden-registry-base"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden storage interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-epochtime = { path = "../../epochtime", version = "0.2.0-alpha" }
ekiden-registry-api = { path = "../api", version = "0.2.0-alpha" }
byteorder = "1"
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
protobuf = "~2.0"
serde = "1.0.71"
serde_derive = "1.0"
