[package]
name = "token-api"
version = "0.1.0-alpha.4"
authors = [
    "Raymond Cheng <me@raymondcheng.net>",
    "Jernej Kos <jernej@kos.mx>"
]
build = "build.rs"

[dependencies]
cargo-cult = "0.1.0"
ekiden-core = { path = "../../../core/common" }
protobuf = "~1.4"
serde = "1.0"

[build-dependencies]
ekiden-tools = { path = "../../../tools" }
