[package]
name = "ekiden-runtime-client"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden runtime client functionality"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
clap = { version = "2.29.1" }
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-core = { path = "../../core/common", version = "0.2.0-alpha" }
ekiden-db-trusted = { path = "../../db/trusted", version = "0.2.0-alpha" }
ekiden-roothash-base = { path = "../../roothash/base", version = "0.2.0-alpha" }
ekiden-tracing = { path = "../../tracing", version = "0.2.0-alpha" }
ekiden-instrumentation = { path = "../../instrumentation", version = "0.2.0-alpha" }
ekiden-instrumentation-prometheus = { path = "../../instrumentation/prometheus", version = "0.2.0-alpha" }
ekiden-keymanager-common = { path = "../../key-manager/common", version = "0.2.0-alpha" }
ekiden-runtime-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-registry-client = { path = "../../registry/client", version = "0.2.0-alpha" }
ekiden-roothash-client = { path = "../../roothash/client", version = "0.2.0-alpha" }
ekiden-scheduler-base = { path = "../../scheduler/base", version = "0.2.0-alpha" }
ekiden-scheduler-client = { path = "../../scheduler/client", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
ekiden-storage-client = { path = "../../storage/client", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
pretty_env_logger = "0.2"
rustracing = "0.1.7"
rustracing_jaeger = { git = "https://github.com/oasislabs/rustracing_jaeger.git", tag = "0.1.7-ekiden1" }
serde = "1.0.71"
serde_cbor = { git = "https://github.com/oasislabs/cbor", tag = "v0.9.0-ekiden1" }
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
grpcio = { version = "~0.4.2", features = ["openssl"] }
protobuf = "~2.0"
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
protoc-grpcio = "0.2.0"

[dev-dependencies]
ekiden-storage-dummy = { path = "../../storage/dummy", version = "0.2.0-alpha" }
