[workspace]
members = [
    "tools",

    # Dependency injection.
    "di",

    # Instrumentation.
    "instrumentation",
    "instrumentation/prometheus",

    # Common.
    "common",
    "common/api",

    # Random beacon.
    "beacon/base",
    "beacon/dummy",

    # Random beacon.
    "beacon/base",
    "beacon/dummy",

    # Consensus interface.
    "consensus/api",
    "consensus/base",
    "consensus/client",
    "consensus/dummy",
    "consensus/optimistic",

    # Storage interface.
    "storage/api",
    "storage/base",
    "storage/dummy",
    "storage/dynamodb",
    "storage/frontend",
    "storage/multilayer",
    "storage/persistent",
    "storage/lru_cache",
    "storage/batch",

    # Enclave loader (+ attestation).
    "enclave/common",
    "enclave/untrusted",
    "enclave/trusted",

    # Epoch Time.
    "epochtime",

    # RPC.
    "rpc/common",
    "rpc/client",
    "rpc/untrusted",
    "rpc/trusted",
    "rpc/edl",

    # Database.
    "db/untrusted",
    "db/trusted",
    "db/edl",

    # Contract invocation.
    "contract/common",
    "contract/client",
    "contract/untrusted",
    "contract/trusted",
    "contract/edl",

    # Core.
    "core/common",
    "core/untrusted",
    "core/trusted",
    "core/edl",

    # Compute node.
    "compute/api",
    "compute",

    # Core contracts.
    "contracts/key-manager",
    "contracts/token",

    # Clients.
    "clients/token",
    "clients/test-long-term",
    "clients/benchmark",

    # Registry.
    "registry/api",
    "registry/base",
    "registry/client",
    "registry/dummy",

    # Scheduler.
    "scheduler/api",
    "scheduler/base",
    "scheduler/client",
    "scheduler/dummy",

    # Stake escrow.
    "stake/api",
    "stake/base",
    "stake/client",
    "stake/dummy",

    # Dummy shared backend node.
    "node/dummy",
    "node/dummy/api",

    # Ethereum backend components.
    "ethereum",
]
exclude = [ "thirdparty" ]
