[workspace]
members = [
    "tools",

    # Common.
    "common",

    # Consensus interface.
    "consensus/base",
    "consensus/dummy",

    # Storage interface.
    "storage/base",
    "storage/dummy",

    # Enclave loader.
    "enclave/common",
    "enclave/untrusted",
    "enclave/trusted",

    # RPC (+ attestation).
    "rpc/common",
    "rpc/client",
    "rpc/untrusted",
    "rpc/trusted",
    "rpc/edl",

    # Database.
    "db/untrusted",
    "db/trusted",
    "db/edl",

    # Core.
    "core/common",
    "core/untrusted",
    "core/trusted",
    "core/edl",

    # Compute node.
    "compute/api",
    "compute",

    # Consensus node (deprecated).
    "consensus/api",
    "consensus",

    # Core contracts.
    "contracts/key-manager",
]
