[workspace]
members = [
    "tools",

    # Dependency injection.
    "di",

    # Instrumentation.
    "instrumentation",
    "instrumentation/prometheus",

    # Tracing.
    "tracing",

    # Common.
    "common",
    "common/api",

    # Root hash interface.
    "roothash/api",
    "roothash/base",
    "roothash/client",

    # Storage interface.
    "storage/api",
    "storage/base",
    "storage/dummy",
    "storage/dynamodb",
    "storage/frontend",
    "storage/multilayer",
    "storage/persistent",
    "storage/lru_cache",
    "storage/batch",

    # Enclave loader (+ attestation).
    "enclave/common",
    "enclave/untrusted",
    "enclave/trusted",
    "enclave/logger",

    # Epoch Time.
    "epochtime",

    # RPC.
    "rpc/api",
    "rpc/common",
    "rpc/client",
    "rpc/untrusted",
    "rpc/trusted",
    "rpc/edl",

    # Database.
    "db/untrusted",
    "db/trusted",
    "db/edl",

    # Runtime invocation.
    "runtime/common",
    "runtime/client",
    "runtime/untrusted",
    "runtime/trusted",
    "runtime/edl",

    # Core.
    "core/common",
    "core/untrusted",
    "core/trusted",
    "core/edl",

    # Compute node.
    "compute/api",
    "compute",

    # Compute worker.
    "worker",

    # Test runtimes.
    "tests/runtimes/token",
    "tests/runtimes/test-db-encryption",
    "tests/runtimes/test-logger",

    # Test clients.
    "tests/clients/token",
    "tests/clients/test-long-term",
    "tests/clients/benchmark",
    "tests/clients/test-db-encryption",
#    "tests/clients/test-logger",

    # Registry.
    "registry/api",
    "registry/base",
    "registry/client",

    # Scheduler.
    "scheduler/api",
    "scheduler/base",
    "scheduler/client",

    # Stake escrow.
    "stake/api",
    "stake/base",
    "stake/client",
    "stake/dummy",

    # Key manager.
    "key-manager/api",
    "key-manager/common",
    "key-manager/client",
    "key-manager/dummy/enclave",
    "key-manager/dummy/untrusted",
    "key-manager/node",
]
exclude = [ "thirdparty" ]

[profile.release]
panic = "abort"
