[package]
name = "ekiden-storage-batch"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden storage interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-epochtime = { path = "../../epochtime", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../base", version = "0.2.0-alpha" }
ekiden-storage-dummy = { path = "../dummy", version = "0.2.0-alpha" }
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
log = "0.4"
