[package]
name = "ekiden-roothash-dummy"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden dummy in-memory root hash backend"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-di = { path = "../../di", version = "0.2.0-alpha" }
ekiden-instrumentation = { path = "../../instrumentation", version = "0.2.0-alpha" }
ekiden-instrumentation-prometheus = { path = "../../instrumentation/prometheus", version = "0.2.0-alpha" }
ekiden-roothash-base = { path = "../base", version = "0.2.0-alpha" }
ekiden-scheduler-base = { path = "../../scheduler/base", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
ekiden-storage-mutablestate = { path = "../../storage/mutablestate", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
log = "0.4"
serde = "1.0.71"
serde_cbor = "0.8.2"
serde_derive = "1.0"
exonum_rocksdb = "~0.7.4"

[dev-dependencies]
ekiden-beacon-base = { path = "../../beacon/base", version = "0.2.0-alpha" }
ekiden-beacon-dummy = { path = "../../beacon/dummy", version = "0.2.0-alpha" }
ekiden-epochtime = { path = "../../epochtime", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
ekiden-registry-dummy = { path = "../../registry/dummy", version = "0.2.0-alpha" }
ekiden-scheduler-dummy = { path = "../../scheduler/dummy", version = "0.2.0-alpha" }
ekiden-storage-dummy = { path = "../../storage/dummy", version = "0.2.0-alpha" }
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
