[package]
name = "ekiden-consensus-dummy"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden dummy in-memory consensus backend"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-di = { path = "../../di", version = "0.2.0-alpha" }
ekiden-consensus-base = { path = "../base", version = "0.2.0-alpha" }
ekiden-scheduler-base = { path = "../../scheduler/base", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
log = "0.4"
serde = "=1.0.59"
serde_cbor = "0.8.2"
serde_derive = "1.0"

[dev-dependencies]
ekiden-beacon-base = { path = "../../beacon/base", version = "0.2.0-alpha" }
ekiden-beacon-dummy = { path = "../../beacon/dummy", version = "0.2.0-alpha" }
ekiden-epochtime = { path = "../../epochtime", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
ekiden-registry-dummy = { path = "../../registry/dummy", version = "0.2.0-alpha" }
ekiden-scheduler-dummy = { path = "../../scheduler/dummy", version = "0.2.0-alpha" }
ekiden-storage-dummy = { path = "../../storage/dummy", version = "0.2.0-alpha" }
grpcio = { git = "https://github.com/ekiden/grpc-rs", tag = "v0.3.0-ekiden2", features = ["openssl"] }
