[package]
name = "ekiden-runtime"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
slog = "2.4.1"
slog-json = "2.3.0"
serde = "1.0.71"
serde_derive = "1.0"
# TODO: Change to released version when 0.10.0 is released.
serde_cbor = { git = "https://github.com/pyfisch/cbor", rev = "114ecaeac53799d0bf81ca8d1b980c7c419d76fe" }
serde_json = "1.0.39"
serde_bytes = "~0.10"
lazy_static = "1.3.0"
crossbeam = "0.7.1"
byteorder = "1.3.1"
failure = "0.1.5"
sgx-isa = { version = "0.2.0", features = ["sgxstd"] }
# TODO: Change version when merged upstream (briansmith/ring#738).
ring = "=0.14.5"
webpki = "0.19.1"
untrusted = "0.6.2"
bincode = "1.0.0"
snow = { version = "0.5.2", default-features = false, features = ["ring-accelerated"] }
percent-encoding = "1.0.1"
pem-iterator = "0.2.0"
chrono = "0.4.6"
base64 = "0.10.1"
rustc-hex = "2.0.1"
# We need aes, block-modes, and crypto-ops as well, since ring doesn't export AES-CTR stuff, nor does it export a secure memset :/
aes-soft = "0.1.0"
block-modes = "0.1.0"
crypto-ops = "0.1.1"
rand = "0.6.5"
futures = "0.1.25"
tokio-current-thread = "0.1.5"
tokio-executor = "0.1.6"
io-context = "0.2.0"
x25519-dalek = "0.5.1"
deoxysii = { git = "https://github.com/oasislabs/deoxysii-rust" }
