[package]
name = "ekiden-rpc-common"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden common RPC functionality"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"
build = "build.rs"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
protobuf = "~2.0"
sodalite = "0.3.0"
byteorder = "1.2.1"
serde = "1.0.71"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
