[package]
name = "ekiden-beacon-base"
version = "0.1.0-alpha.4"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden random beacon interface traits"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
cargo-cult = "0.1.0"
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
