[package]
name = "ekiden-keymanager-edl"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"
description = "EDL additions for the dummy key manager"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
sgx_edl = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.5-ekiden1" }

ekiden-edl = { path = "../../../core/edl" }
