[package]
name = "ekiden-keymanager-client"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden key manager client"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-rpc-client = { path = "../../rpc/client", version = "0.2.0-alpha" }
ekiden-rpc-common = { path = "../../rpc/common", version = "0.2.0-alpha" }
ekiden-keymanager-api = { path = "../api", version = "0.2.0-alpha" }
ekiden-keymanager-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-enclave-logger = { path = "../../enclave/logger", version = "0.2.0-alpha" }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
serde = "1.0.71"
serde_cbor = "0.8.2"

[target.'cfg(target_env = "sgx")'.dependencies]
ekiden-rpc-trusted = { path = "../../rpc/trusted", version = "0.2.0-alpha" }
