[package]
name = "ekiden-rpc-client"
version = "0.1.0-alpha.4"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden RPC client"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"

[dependencies]
cargo-cult = "0.1.0"
ekiden-common = { path = "../../common", version = "0.1.0-alpha.4" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.1.0-alpha.4" }
ekiden-rpc-common = { path = "../common", version = "0.1.0-alpha.4" }
protobuf = "~1.4"
sodalite = "0.3.0"
serde = "1.0"
serde_cbor = "0.8.2"

[target.'cfg(target_env = "sgx")'.dependencies]
futures-sgx = { git = "https://github.com/ekiden/futures-rs" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-compute-api = { path = "../../compute/api", version = "0.1.0-alpha.4" }
byteorder = "1.2.1"
futures = "0.1"
grpcio = "0.2.2"
rand = "0.4"
tokio-core = "0.1"
