[package]
name = "ekiden-rpc-client"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden RPC client"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-rpc-common = { path = "../common", version = "0.2.0-alpha" }
protobuf = "~2.0"
sodalite = "0.3.0"
serde = "1.0.71"
serde_cbor = "0.8.2"

[target.'cfg(target_env = "sgx")'.dependencies]
futures-sgx = { git = "https://github.com/oasislabs/futures-rs" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
ekiden-rpc-api = { path = "../api", version = "0.2.0-alpha" }
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
byteorder = "1.2.1"
futures = "0.1"
rand = "0.4"
