[package]
name = "ekiden-keymanager-node"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden key manager node"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"
build = "build.rs"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-di = { path = "../../di", version = "0.2.0-alpha" }
ekiden-enclave-common = { path = "../../enclave/common", version = "0.2.0-alpha" }
ekiden-rpc-client = { path = "../../rpc/client", version = "0.2.0-alpha" }
ekiden-rpc-common = { path = "../../rpc/common", version = "0.2.0-alpha" }
ekiden-rpc-api = { path="../../rpc/api", version = "0.2.0-alpha" }
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
ekiden-keymanager-api = { path = "../api", version = "0.2.0-alpha" }
ekiden-keymanager-common = { path = "../common", version = "0.2.0-alpha" }
ekiden-keymanager-client = { path = "../client", version = "0.2.0-alpha" }
ekiden-keymanager-untrusted = { path = "../dummy/untrusted" }
ekiden-storage-frontend = { path = "../../storage/frontend", version = "0.2.0-alpha" }
ekiden-storage-persistent = { path = "../../storage/persistent", version = "0.2.0-alpha" }
ekiden-untrusted = { path = "../../core/untrusted", version = "0.2.0-alpha" }
ekiden-storage-base = { path = "../../storage/base", version = "0.2.0-alpha" }
base64 = "0.9.0"
clap = "2.29.1"
futures = "0.1"
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = "0.4"
lru-cache = "0.1.1"
pretty_env_logger = "0.2"
protobuf = "~2.0"
reqwest = "0.8.2"
serde = "1.0"
serde_derive = "1.0"
serde_cbor = { git = "https://github.com/oasislabs/cbor", tag = "v0.9.0-ekiden1" }
sgx_types = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
thread_local = "0.3.5"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.2.0-alpha" }
ekiden-edl = { path = "../../core/edl", version = "0.2.0-alpha" }

[[bin]]
name = "ekiden-keymanager-test-client"
path = "src/bin/test-client.rs"

[[bin]]
name = "ekiden-keymanager-node"
path = "src/main.rs"
