[package]
name = "ekiden-scheduler-dummy"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden scheduler dummt backend"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
ekiden-di = { path = "../../di", version = "0.2.0-alpha" }
ekiden-core = { path = "../../core/common", version = "0.2.0-alpha" }
ekiden-beacon-base = { path = "../../beacon/base", version = "0.2.0-alpha" }
ekiden-epochtime = { path = "../../epochtime", version = "0.2.0-alpha" }
ekiden-registry-base = { path = "../../registry/base", version = "0.2.0-alpha" }
ekiden-scheduler-base = { path = "../base", version = "0.2.0-alpha" }
log = "0.4"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
rand = "0.4.2"

[dev-dependencies]
ekiden-beacon-dummy = { path = "../../beacon/dummy", version = "0.2.0-alpha" }
ekiden-registry-dummy = { path = "../../registry/dummy", version = "0.2.0-alpha" }
ekiden-grpcio = { version = "0.3.2", features = ["openssl"] }
serde = "=1.0.59"
serde_cbor = "0.8.2"
