[package]
name = "ekiden-compute-api"
version = "0.1.0-alpha.4"
authors = ["Ekiden Developers <ekiden-dev@googlegroups.com>"]
description = "Ekiden compute node API"
keywords = ["ekiden"]
repository = "https://github.com/ekiden/ekiden"
build = "build.rs"

[dependencies]
cargo-cult = "0.1.0"
protobuf = "~1.4"
grpcio = "0.2.2"
futures = "0.1"

[build-dependencies]
ekiden-tools = { path = "../../tools", version = "0.1.0-alpha.4" }
protoc-grpcio = "0.1.0"
