# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.2"

[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "v0.9.2"

# iavl as of 2018/07/12 wants `=0.22.0-rc2`, so override it.
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "v0.22.3"

# https://github.com/tendermint/tendermint/issues/1777
[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[prune]
  go-tests = true
  unused-packages = true
