############################################
# Single node configuration for development.
############################################
#
# NOTE: This sets up a single node that is a Tendermint validator,
#       a storage node and an Ekiden worker at the same time. In
#       actual deployments these nodes will likely run separately.
#
datadir: /tmp/ekiden-node-data

# Logging.
# Per-module log levels are defined below. If you prefer just one unified log level, you can use:
# log:
#   level: debug
log:
  level:
    # Per-module log levels. Longest prefix match will be taken. Fallback to "default", if no match.
    default: debug
    tendermint: warn
    tendermint/context: error

# Internal gRPC services.
grpc:
  log:
    verbose_debug: true

# Worker configuration.
worker:
  backend: sandboxed
  binary: /code/target/debug/ekiden-worker
  runtime:
    id: "0000000000000000000000000000000000000000000000000000000000000000"
    binary: /code/target/enclave/simple-keyvalue.so
    replica_group_size: 1
    replica_group_backup_size: 0
  client:
    port: 9200
    addresses:
      - "127.0.0.1:9200"
  p2p:
    port: 9100
  key_manager:
    address: "127.0.0.1:9003"
    certificate: /code/tests/keymanager/km.pem

# Epochtime backend.
epochtime:
  backend: tendermint
  tendermint:
    # This makes each epoch last for 30 tendermint blocks.
    interval: 30

# Random beacon backend.
beacon:
  backend: tendermint

# Storage backend.
storage:
  backend: memory

# Scheduler backend.
scheduler:
  backend: trivial

# Registry backend.
registry:
  backend: tendermint

# Roothash backend.
roothash:
  backend: tendermint

# Tendermint backend configuration.
tendermint:
  consensus:
    timeout_commit: 1s
