[package]
name = "ekiden-keymanager-common"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "common util for keymanager (available to both enclave and non-enclave part)"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"

[dependencies]
sodalite = "0.3.0"
ekiden-common = { path = "../../common", version = "0.2.0-alpha" }
serde = "1.0.71"
serde_derive = "1.0"
