[package]
name = "ekiden-tools"
version = "0.2.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
description = "Ekiden build tools"
keywords = ["ekiden"]
repository = "https://github.com/oasislabs/ekiden"
build = "build.rs"

[dependencies]
mktemp = "0.3.1"
cc = "1.0"
# (pinning transitive dependency) backtrace-sys 0.1.24 compatible with backtrace 0.3.9
backtrace-sys = "=0.1.24"
# (pinning transitive dependency) backtrace 0.3.10 incompatible with failure 0.1
backtrace = "=0.3.9"
# (pinning transitive dependency) time 0.1.41 is broken?
time = "=0.1.40"
# (pinning transitive dependency) rustc-demangle 0.1.10 requires `rename-dependency` feature
rustc-demangle = "=0.1.9"
# (pinning transitive dependency) in 0.4.18,
# error[E0658]: use of unstable library feature 'proc_macro' (see issue #38356)
proc-macro2 = "=0.4.17"
protoc = "~2.0"
protoc-rust = "~2.0"
protobuf = "~2.0"
sgx_edl = { git = "https://github.com/oasislabs/rust-sgx-sdk", tag = "v1.0.1-ekiden3" }
clap = "2.29.1"
ansi_term = "0.11"
toml = "0.4"
serde = "1.0.71"
serde_derive = "1.0"
error-chain = "0.12.0"
filebuffer = "0.3"
regex = "=1.0.0"
rustc-hex = "1.0.0"

[[bin]]
name = "cargo-ekiden"
path ="bin/main.rs"
